# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-10-15 17:24
from __future__ import unicode_literals

from django.db import migrations, models
import mathapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('mathapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField()),
                ('image', models.ImageField(blank=True, null=True, upload_to=mathapp.models.generic_filename)),
            ],
        ),
    ]
