# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-10-15 18:36
from __future__ import unicode_literals

from django.db import migrations, models
import mathapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('mathapp', '0003_elementary_math_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Beginner_math',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('slug', models.SlugField()),
                ('image', models.ImageField(blank=True, null=True, upload_to=mathapp.models.generic_filename)),
                ('content', models.TextField()),
                ('question1', models.TextField(blank=True, null=True)),
                ('answer1', models.IntegerField(blank=True, null=True)),
                ('block1', models.TextField(blank=True, null=True)),
                ('question2', models.TextField(blank=True, null=True)),
                ('answer2', models.IntegerField(blank=True, null=True)),
                ('block2', models.TextField(blank=True, null=True)),
                ('question3', models.TextField(blank=True, null=True)),
                ('answer3', models.IntegerField(blank=True, null=True)),
                ('block3', models.TextField(blank=True, null=True)),
                ('question4', models.TextField(blank=True, null=True)),
                ('answer4', models.IntegerField(blank=True, null=True)),
                ('block4', models.TextField(blank=True, null=True)),
                ('question5', models.TextField(blank=True, null=True)),
                ('answer5', models.IntegerField(blank=True, null=True)),
                ('block5', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
