# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-10-15 18:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mathapp', '0004_beginner_math'),
    ]

    operations = [
        migrations.AddField(
            model_name='beginner_math',
            name='video',
            field=models.TextField(null=True),
        ),
    ]
