# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-10-16 15:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mathapp', '0005_beginner_math_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='elementary_math',
            name='users_reaction',
            field=models.ManyToManyField(blank=True, null=True, related_name='users_reaction', to=settings.AUTH_USER_MODEL),
        ),
    ]
