# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-10-22 16:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mathapp', '0006_elementary_math_users_reaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='text',
            field=models.TextField(null=True),
        ),
    ]
