# Generated by Django 2.2.6 on 2019-11-18 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mathapp', '0009_auto_20191118_2250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='email',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='last_name',
        ),
    ]
