# Generated by Django 2.2.6 on 2019-11-28 19:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mathapp', '0010_auto_20191118_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logged_in_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='UserAll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False)),
                ('exam1', models.IntegerField(default=0)),
                ('exam2', models.IntegerField(default=0)),
                ('exam3', models.IntegerField(default=0)),
                ('exam4', models.IntegerField(default=0)),
                ('exam5', models.IntegerField(default=0)),
                ('exam6', models.IntegerField(default=0)),
                ('exam7', models.IntegerField(default=0)),
                ('exam8', models.IntegerField(default=0)),
                ('exam9', models.IntegerField(default=0)),
                ('exam10', models.IntegerField(default=0)),
                ('exam11', models.IntegerField(default=0)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
