# Generated by Django 2.2.6 on 2019-11-28 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mathapp', '0011_auto_20191129_0135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='active',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='exam1',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='exam10',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='exam11',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='exam2',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='exam3',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='exam4',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='exam5',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='exam6',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='exam7',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='exam8',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='exam9',
        ),
    ]
