# Generated by Django 2.2.6 on 2019-12-16 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mathapp', '0012_auto_20191129_0151'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Quiz',
        ),
    ]
