# Generated by Django 2.2.6 on 2019-12-16 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mathapp', '0014_quiz'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Quiz',
        ),
    ]
