# Generated by Django 2.2.6 on 2020-01-18 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mathapp', '0017_auto_20200118_1906'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='title',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
